#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

# Create a bilibop-specific temporary directory (in /run), and populate it.

### BEGIN ###

. /lib/bilibop/common.sh
get_bilibop_variables ${rootmnt}
udev_root="/dev"

mkdir -p "${BILIBOP_RUNDIR}"

# Create a fake device map (optional, but enabled by default):
[ "${BILIBOP_RULES_FAKE_DEVICE_MAP}" = "false" ] ||
echo "(hd0)	$(physical_hard_disk ${rootmnt})" >${BILIBOP_RUNDIR}/grub-device.map

# Create two non-empty files. This last action is not absolutely necessary,
# but avoids some udev complaints.
for	rules in cd.rules net.rules
do	echo "# unpersistent-${rules}" >${BILIBOP_RUNDIR}/unpersistent-${rules}
done

:
### END ###
