etc/xdg/autostart/lockfs-notify.desktop				etc/xdg/autostart
etc/grub.d/*				etc/grub.d
usr/libexec/bilibop/lockfs_mount_helper				usr/libexec/bilibop
usr/lib/bilibop/lockfs.sh					usr/lib/bilibop
usr/bin/lockfs-notify						usr/bin
usr/share/initramfs-tools/hooks/bilibop-lockfs			usr/share/initramfs-tools/hooks
usr/share/initramfs-tools/scripts/init-top/bilibop-lockfs	usr/share/initramfs-tools/scripts/init-top
usr/share/initramfs-tools/scripts/local-bottom/bilibop-lockfs	usr/share/initramfs-tools/scripts/local-bottom
