#!/bin/sh -e
# Output the underlying disk name of the root filesystem or of the
# file/device/directory given as argument.
PATH="/sbin:/bin"
. /lib/bilibop/common.sh
get_udev_root
physical_hard_disk ${1}
