#!/bin/sh
# Output the underlying disk name of the root filesystem or of the
# file/device/directory given as argument.
. /lib/bilibop/common.sh
get_udev_root
DISK="$(physical_hard_disk ${1:-/})" || exit $?
echo "${DISK}" | sed "s,^${udev_root}/,,"
