#!/bin/sh

PREREQ="klibc"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

# Add bilibop functions and needed commands to use them. This hook is a part
# of bilibop-common, even if there is no bilibop-common script to include in
# the initramfs, to not duplicate its content for each other bilibop-* package.

### BEGIN ###
. /usr/share/initramfs-tools/hook-functions

# Copy the common bilibop functions file
cp --parents /lib/bilibop/common.sh ${DESTDIR}

# Add commands needed by the bilibop functions. This depends if busybox is
# added too or not.
if	[ "${BUSYBOX}" = "n" -o ! -e ${BUSYBOXDIR}/busybox ]
then
	copy_exec /bin/df	/bin
	copy_exec /bin/grep	/bin
	copy_exec /bin/sed	/bin
	# replace klibc's 'readlink':
	rm -f ${DESTDIR}/bin/readlink
	copy_exec /bin/readlink	/bin
fi

# This is already done by the udev's hook:
#copy_exec /sbin/udevadm	/sbin

# Be sure the removable media hosting the system can be managed:
force_load usb-storage
force_load firewire-sbp2
force_load mmc_block

:
### END ###
